# Generated by Django 5.2 on 2025-05-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='username',
        ),
    ]
