# Generated by Django 5.2 on 2025-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
