# Generated by Django 5.2 on 2025-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reminder_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
