# Generated by Django 5.2 on 2025-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal_term', models.CharField(blank=True, max_length=100)),
                ('reminder_frequency', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
