# Generated by Django 5.2 on 2025-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='reminder',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='term',
            field=models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year'), ('2 years', '2 years')], max_length=20),
        ),
    ]
