# Generated by Django 5.2 on 2025-05-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_saving_user'),
        ('savings', '0003_remove_savingsgoal_created_at_and_more'),
    ]

    operations = [
    ]
