# Generated by Django 5.2 on 2025-05-11 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_savingsgoal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='category',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='goal_term',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='reminder_frequency',
        ),
        migrations.AddField(
            model_name='saving',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='savings.savingsgoal'),
        ),
    ]
