# Generated by Django 5.2 on 2025-05-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_remove_transaction_username'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
