# Generated by Django 5.2 on 2025-05-11 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfinance',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyfinance',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyfinance',
            name='month',
            field=models.DateField(default=datetime.date.today, verbose_name='Month'),
        ),
        migrations.DeleteModel(
            name='MonthlySpending',
        ),
    ]
